# Generated by Django 4.2.26 on 2025-12-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_user_id_dd1b42_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
    ]
